apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sekhar5031/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: mongodb://root:example@mongodb:27017